"""Curated example story seeds for onboarding/demo flows."""

EXAMPLE_STORIES: list[dict[str, object]] = [
    {
        "id": "fractured-crown",
        "title": "The Fractured Crown",
        "description": "A dark fantasy succession struggle under a blood-bound eclipse.",
        "genre": "dark_fantasy",
        "world_era": "medieval",
        "world_essence": ["political_intrigue", "prophecy_and_destiny"],
        "protagonist_archetype": "outcast",
        "protagonist_virtues": ["resolute", "cunning"],
        "protagonist_shadow": "grief",
        "spark": "The eclipse seals the royal citadel, and only an exiled heir can reopen the gates.",
        "chapter_length": "medium",
        "writing_style": "literary_fiction",
    },
    {
        "id": "clockwork-vow",
        "title": "Clockwork Vow",
        "description": "Steampunk rebellion where a runic engine predicts betrayals.",
        "genre": "steampunk",
        "world_era": "victorian",
        "world_essence": ["political_intrigue", "exploration"],
        "protagonist_archetype": "scholar",
        "protagonist_virtues": ["curious", "patient"],
        "protagonist_shadow": "obsession",
        "spark": "A forbidden engine writes tomorrow's traitor name each dawn, and today it writes yours.",
        "chapter_length": "medium",
        "writing_style": "pulp_adventure",
    },
    {
        "id": "void-lighthouse",
        "title": "The Void Lighthouse",
        "description": "Cosmic sci-fi survival around a dead beacon at the edge of mapped space.",
        "genre": "cosmic_sci_fi",
        "world_era": "futuristic",
        "world_essence": ["survival", "exploration"],
        "protagonist_archetype": "warrior",
        "protagonist_virtues": ["fearless", "loyal"],
        "protagonist_shadow": "distrust",
        "spark": "A silent lighthouse reactivates in deep space and starts transmitting your childhood memories.",
        "chapter_length": "long",
        "writing_style": "epic_fantasy",
    },
    {
        "id": "jade-tribunal",
        "title": "Jade Tribunal",
        "description": "Wuxia courtroom duel between sect honor and forbidden cultivation.",
        "genre": "wuxia_xianxia",
        "world_era": "ancient",
        "world_essence": ["political_intrigue", "sword_and_sorcery"],
        "protagonist_archetype": "seer",
        "protagonist_virtues": ["empathic", "charismatic"],
        "protagonist_shadow": "hubris",
        "spark": "At the celestial tribunal, your master confesses to a crime only your future self could commit.",
        "chapter_length": "medium",
        "writing_style": "poetic_prose",
    },
]
